services:
  - name: mariadb
    type: private_service
    env: docker
    image: mariadb:10.7
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: your_root_password
      - key: MYSQL_DATABASE
        value: glpi
      - key: MYSQL_USER
        value: your_user
      - key: MYSQL_PASSWORD
        value: your_password
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 5
    restartPolicy: always

  - name: glpi
    type: web
    env: docker
    image: diouxx/glpi
    envVars:
      - key: GLPI_DB_HOST
        value: mariadb
      - key: GLPI_DB_NAME
        value: glpi
      - key: GLPI_DB_USER
        value: your_user
      - key: GLPI_DB_PASSWORD
        value: your_password
      - key: TIMEZONE
        value: Europe/Brussels
    disk:
      name: glpi-data
      mountPath: /var/www/html/glpi
      sizeGB: 5
    restartPolicy: always
    healthCheckPath: "/install/install.php"
