services:
  - name: glpi
    type: web
    env: docker
    image: diouxx/glpi
    envVars:
      - key: GLPI_DB_HOST
        value: YOUR_RENDER_DB_HOST
      - key: GLPI_DB_NAME
        value: YOUR_DATABASE_NAME
      - key: GLPI_DB_USER
        value: YOUR_DATABASE_USER
      - key: GLPI_DB_PASSWORD
        value: YOUR_DATABASE_PASSWORD
      - key: TIMEZONE
        value: Europe/Brussels
    disk:
      name: glpi-data
      mountPath: /var/www/html/glpi
      sizeGB: 1
    healthCheckPath: "/install/install.php"
